#!/usr/bin/env python3
"""Generate a review-only emotion table from the audited saved TEST results.

Nothing is written into the manuscript. Regenerate with --results and --output.
"""
import argparse
import csv
import json
import math
import statistics
from pathlib import Path

ROOT=Path(__file__).resolve().parents[4]
OUT=ROOT/'artifacts/segmenter/nonasr_boundary_audit_2026-09-12'
LABELS={'nods_50hz':'Native frames','fixed_25hz':'Fixed stride 2',
        'fixed_10hz':'Fixed stride 5','fixed_5hz':'Fixed stride 10',
        'learned_frozen':'Frozen ASR policy','learned_grpo':'Emotion GRPO'}


def fmt(value,places):
    if value is None or not math.isfinite(value):return '--'
    return f'{value:.{places}f}'


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--results',type=Path,default=OUT/'checkpoint_audit.json')
    p.add_argument('--output',type=Path,default=OUT/'emotion_results.tex')
    p.add_argument('--compact',action='store_true',help='Omit the redundant 25-Hz row in the proposed paper table')
    a=p.parse_args()
    runs=json.loads(a.results.read_text())['runs']
    summary={};csvrows=[]
    for task in ['emotion','speaker_count','intent']:
        summary[task]={}
        for arm in LABELS:
            rs=sorted((r for r in runs if r['task']==task and r['arm']==arm),key=lambda r:r['seed'])
            assert len(rs)==3
            v=[r['test'][r['metric']] for r in rs]
            hz=[r['test']['f_audio_hz_'+task] for r in rs]
            row=dict(metric_mean=statistics.mean(v),metric_sd=statistics.stdev(v),metric_seeds=v,
                     hz_mean=statistics.mean(hz),hz_sd=statistics.stdev(hz),hz_seeds=hz)
            summary[task][arm]=row
            csvrows.append(dict(task=task,arm=arm,metric=rs[0]['metric'],mean=row['metric_mean'],
                                sd=row['metric_sd'],hz=row['hz_mean'],hz_sd=row['hz_sd'],seeds=3))
    a.output.parent.mkdir(parents=True,exist_ok=True)
    (a.output.parent/'task_results_summary.json').write_text(json.dumps(summary,indent=2)+'\n')
    with (a.output.parent/'task_results.csv').open('w') as f:
        w=csv.DictWriter(f,fieldnames=list(csvrows[0]));w.writeheader();w.writerows(csvrows)
    lines=[r'% Generated by make_table_nonasr_audit.py; mean +/- sample SD, three seeds.',
           r'% CREMA-D voice-vote test, n=1431; checkpoint selection on validation macro-F1.',
           r'\begin{tabular}{lrr}',r'\toprule',r'Policy & Tokens/s & Macro-F1 (\%) \\',r'\midrule']
    for arm,name in LABELS.items():
        if a.compact and arm=='fixed_25hz':continue
        r=summary['emotion'][arm]
        if arm=='learned_frozen':lines.append(r'\midrule')
        lines.append(f"{name} & {fmt(r['hz_mean'],2)} & $"+fmt(100*r['metric_mean'],1)+r' \pm '+fmt(100*r['metric_sd'],1)+r'$ \\')
    lines.extend([r'\bottomrule',r'\end{tabular}'])
    assert all(line.count('&')==2 for line in lines if '&' in line)
    a.output.write_text('\n'.join(lines)+'\n')
    print('Wrote',a.output)


if __name__=='__main__':main()
